builds:
  - id: sleeping-beauty
    main: ./cmd/sleepingd
    binary: sleepingd
nfpms:
  - vendor: Radian LLC
    maintainer: &author Radian LLC <contact+sleeping-beauty@radian.codes>
    description: &description Webserver auto-sleep for containerized environments
    license: &license MIT
    formats:
      - apk
      - deb
      - rpm
snapcrafts:
  - publish: false
    summary: *description
    description: *description
    confinement: classic
    license: *license
dockers:
  - image_templates:
      - "radiansoftware/sleeping-beauty:latest"
      - "radiansoftware/sleeping-beauty:{{ .Tag }}"
checksum:
  name_template: "checksums.txt"
