name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Authenticate to GHCR
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u radian-software --password-stdin
      - name: Ensure project compiles
        run: "make"
      - name: Pull image for unit and integration tests
        run: |
          image="$(< ./test/integration/ci_image)"
          docker pull "${image}"
          docker tag "${image}" sleeping-beauty-integration-test:latest
      # Pass -v because some tests might hang if they were implemented
      # incorrectly, and debugging this will be a lot easier if you
      # can see the incomplete log output.
      - name: Unit tests
        run: "make test-unit TEST_FLAGS=-v"
      - name: Integration tests
        run: "make test-integration TEST_FLAGS=-v"
