name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull image for integration tests
        run: |
          image="$(< ./test/integration/ci_image)"
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u radian-software --password-stdin
          docker pull "${image}"
          docker tag "${image}" sleeping-beauty-integration-test:latest
      - name: Unit tests
        run: "make test-unit"
      - name: Integration tests
        run: "make test-integration"
