name: CI
on:
  push:
    branches:
      - main
  pull_request: {}
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Authenticate to GHCR
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u radian-software --password-stdin
      - name: Pull image for unit and integration tests
        run: |
          image="$(< ./test/integration/ci_image)"
          docker pull "${image}"
          docker tag "${image}" sleeping-beauty-integration-test:latest
      - name: Unit tests
        run: "./docker/run_in_docker.bash sleeping-beauty-integration-test:latest make test-unit"
      - name: Integration tests
        run: "make test-integration"
